In [16]:
import sys
import os


repo_root = os.path.abspath("..")   
sys.path.append(repo_root)

from src.feature_engineering_2 import build_player_team_map_from_events, compute_features_for_all_events, parse_match_id_from_unique, compute_snapshot_features_for_event, build_frames_dict, group_tracking_by_match_and_frame
import pandas as pd

In [17]:
events = pd.read_csv("../Our Datasets/processed_recoverys_and_interceptions_dynamic_events.csv")
tracking = pd.read_csv("../Our Datasets/processed_tracking_data_start.csv")

In [18]:
events

,phase_index,player_possession_phase_index,event_type,event_subtype,start_type,end_type,pass_outcome,team_shortname,first_player_possession_in_team_possession,last_player_possession_in_team_possession,...,team_out_of_possession_phase_type,n_teammates_ahead_start,n_opponents_ahead_start,max_player_targeted_xthreat,player_targeted_dangerous.1,n_passing_options_dangerous_not_difficult.1,team_id.1,Unique ID,possession_start,possession_end
0,6,1.0,player_possession,NaN,recovery,pass,successful,Newcastle,True,False,...,high_block,9.0,10.0,0.0024,0.0,0.0,1805,1886347_42_46,387,504
1,6,2.0,player_possession,NaN,pass_reception,pass,successful,Newcastle,False,False,...,high_block,9.0,10.0,0.0024,0.0,0.0,1805,1886347_42_46,387,504
2,7,1.0,player_possession,NaN,pass_reception,pass,unsuccessful,Newcastle,False,True,...,high_block,9.0,10.0,0.0024,0.0,0.0,1805,1886347_42_46,387,504
3,20,1.0,player_possession,NaN,recovery,pass,successful,Newcastle,True,False,...,chaotic,0.0,0.0,0.0091,0.0,0.0,1805,1886347_170_193,1492,1606
4,20,2.0,player_possession,NaN,pass_reception,pass,successful,Newcastle,False,False,...,chaotic,0.0,0.0,0.0091,0.0,0.0,1805,1886347_170_193,1492,1606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5850,403,1.0,player_possession,NaN,recovery,pass,unsuccessful,Auckland FC,True,True,...,chaotic,4.0,8.0,NaN,NaN,0.0,4177,2017461_3747_3747,65560,65560
5851,406,2.0,player_possession,NaN,pass_interception,pass,unsuccessful,Melbourne V FC,True,True,...,chaotic,7.0,8.0,NaN,NaN,0.0,868,2017461_3782_3782,65920,65920
5852,414,8.0,player_possession,NaN,recovery,pass,unsuccessful,Auckland FC,True,True,...,chaotic,7.0,10.0,0.0133,0.0,0.0,4177,2017461_3837_3837,66806,66806
5853,420,1.0,player_possession,NaN,pass_interception,pass,unsuccessful,Melbourne V FC,True,True,...,disruption,3.0,6.0,NaN,NaN,0.0,868,2017461_3932_3932,67716,67716
5854,432,1.0,player_possession,NaN,pass_interception,pass,unsuccessful,Auckland FC,True,True,...,disruption,8.0,10.0,NaN,NaN,0.0,4177,2017461_4095_4095,69308,69308

In [19]:
sample_unique = events['Unique ID'].dropna().iloc[0]
match_id = parse_match_id_from_unique(sample_unique)

In [20]:
ev_match = events[events['Unique ID'].str.startswith(str(match_id))]
tr_match = tracking[tracking['match_id']==match_id]

In [21]:
ev_row = ev_match.iloc[5]
feat = compute_snapshot_features_for_event(ev_row, build_frames_dict(tr_match, match_id), sorted(tr_match['frame'].unique()), build_player_team_map_from_events(events, match_id))
feat

{'error': 'frame_missing'}

In [22]:
feats_df = compute_features_for_all_events(
    "../Our Datasets/processed_recoverys_and_interceptions_dynamic_events.csv",
    "../Our Datasets/processed_tracking_data_start.csv"
)
  
feats_df.head()

Loading events...
Loading tracking snapshot...
Found 5855 rows with errors (player/frame issues). They will remain flagged.

,error,Unique ID,event_row_index,max_player_targeted_xthreat,player_targeted_dangerous,n_passing_options_dangerous_not_difficult
0,no_player_id,1886347_42_46,0,NaN,NaN,NaN
1,no_player_id,1886347_42_46,1,NaN,NaN,NaN
2,no_player_id,1886347_42_46,2,NaN,NaN,NaN
3,no_player_id,1886347_170_193,3,NaN,NaN,NaN
4,no_player_id,1886347_170_193,4,NaN,NaN,NaN

In [23]:
feats_df

,error,Unique ID,event_row_index,max_player_targeted_xthreat,player_targeted_dangerous,n_passing_options_dangerous_not_difficult
0,no_player_id,1886347_42_46,0,NaN,NaN,NaN
1,no_player_id,1886347_42_46,1,NaN,NaN,NaN
2,no_player_id,1886347_42_46,2,NaN,NaN,NaN
3,no_player_id,1886347_170_193,3,NaN,NaN,NaN
4,no_player_id,1886347_170_193,4,NaN,NaN,NaN
...,...,...,...,...,...,...
5850,no_player_id,2017461_3747_3747,5850,NaN,NaN,NaN
5851,no_player_id,2017461_3782_3782,5851,NaN,NaN,NaN
5852,no_player_id,2017461_3837_3837,5852,NaN,NaN,NaN
5853,no_player_id,2017461_3932_3932,5853,NaN,NaN,NaN
5854,no_player_id,2017461_4095_4095,5854,NaN,NaN,NaN

735578

In [24]:
#feats_df.to_parquet("Our Datasets/features_sample_match.parquet", index=False)
feats_df.to_csv("../Our Datasets/features_sample_match_new.csv", index=False)