In [30]:
import pandas as pd
import json
import numpy as np

results_df = pd.read_csv('../../Our Datasets/classifier_results_logreg.csv')

possible_match_ids = [1886347, 1899585]

match_id = possible_match_ids[0]

results_df = results_df[results_df['match_id'] == match_id]

results_df.drop(columns=['match_id', 'row_index', 'Unique ID', 'event_index', 'source_file', 'event_row_index', 'rec_team_id', 'true_value'], inplace=True)

results_df

,predicted_class,predicted_probability,frame_start,frame_end,rec_player_id,rec_team_short,dist_to_attacking_goal,team_out_of_possession_phase_type,player_targeted_dangerous,is_drawing,is_middle_third
0,0,0.196989,387.0,430.0,735578.0,Newcastle,99.575170,high_block,0.0,1,0
1,1,0.818607,1492.0,1492.0,735574.0,Newcastle,34.427403,chaotic/disruption,0.0,1,0
2,1,0.524581,3799.0,3799.0,50978.0,Newcastle,51.188596,chaotic/disruption,1.0,1,1
3,1,0.553058,3854.0,3866.0,38673.0,Auckland FC,47.054798,chaotic/disruption,1.0,1,1
4,1,0.555331,4452.0,4452.0,795507.0,Newcastle,72.213891,medium_block,1.0,1,1
5,1,0.504472,7480.0,7480.0,735573.0,Newcastle,53.900933,chaotic/disruption,0.0,1,1
6,1,0.874515,8011.0,8011.0,51649.0,Newcastle,18.581808,chaotic/disruption,0.0,1,0
7,1,0.866691,9289.0,9301.0,23418.0,Auckland FC,30.829612,low_block,0.0,1,0
8,0,0.323647,9686.0,9696.0,50978.0,Newcastle,75.306988,high_block,0.0,1,0
9,0,0.338456,10163.0,10170.0,795507.0,Newcastle,72.861567,high_block,0.0,1,0
10,0,0.225507,10754.0,10754.0,14736.0,Auckland FC,92.865712,high_block,0.0,1,0
11,1,0.653909,11857.0,11887.0,51667.0,Auckland FC,56.956145,medium_block,0.0,1,1
12,1,0.737117,12012.0,12012.0,735574.0,Newcastle,76.095721,medium_block,0.0,1,0
13,0,0.425580,16811.0,16823.0,176224.0,Newcastle,97.786385,chaotic/disruption,1.0,1,0
14,0,0.417301,17743.0,17743.0,966120.0,Newcastle,65.697584,chaotic/disruption,0.0,1,1
15,1,0.723137,19986.0,19986.0,38673.0,Auckland FC,45.116494,medium_block,1.0,1,1
16,1,0.523097,20199.0,20199.0,966120.0,Newcastle,83.660194,chaotic/disruption,1.0,1,0
17,0,0.393576,20549.0,20556.0,51009.0,Newcastle,101.930031,chaotic/disruption,0.0,1,0
18,0,0.177878,23185.0,23280.0,51649.0,Newcastle,102.307695,high_block,1.0,1,0
19,1,0.724282,28619.0,28647.0,285188.0,Auckland FC,77.325422,medium_block,1.0,1,0
20,1,0.618211,29047.0,29047.0,735573.0,Newcastle,94.150176,medium_block,1.0,1,0
21,1,0.928028,29048.0,29094.0,14736.0,Auckland FC,20.097771,medium_block,1.0,1,0
22,1,0.574078,29369.0,29369.0,795505.0,Newcastle,84.148935,low_block,1.0,1,0
23,0,0.281030,29473.0,29477.0,965685.0,Auckland FC,46.435548,high_block,0.0,1,1
24,1,0.711460,30012.0,30012.0,965685.0,Auckland FC,44.894869,medium_block,0.0,1,1
25,1,0.667639,32947.0,32953.0,50983.0,Newcastle,52.057554,medium_block,1.0,1,1
26,0,0.377132,35339.0,35339.0,285188.0,Auckland FC,102.293708,chaotic/disruption,0.0,1,0
27,1,0.820613,36644.0,36644.0,133501.0,Auckland FC,30.210637,chaotic/disruption,1.0,1,0
28,1,0.964283,47322.0,47322.0,38673.0,Auckland FC,39.455101,transition/quick_break,1.0,1,0
29,1,0.891653,47570.0,47570.0,795506.0,Newcastle,81.294803,transition/quick_break,1.0,1,0
30,0,0.277043,47726.0,47726.0,735573.0,Newcastle,78.931202,high_block,1.0,1,0
31,0,0.172894,47920.0,47920.0,285188.0,Auckland FC,100.411562,high_block,0.0,1,0
32,0,0.269521,49312.0,49312.0,560992.0,Newcastle,80.038756,high_block,0.0,1,0
33,0,0.178208,50131.0,50163.0,795505.0,Newcastle,65.567423,high_block,0.0,1,1
34,1,0.893317,56777.0,56825.0,14736.0,Auckland FC,70.220155,transition/quick_break,1.0,0,1
35,1,0.869471,57138.0,57138.0,43829.0,Auckland FC,38.683967,chaotic/disruption,0.0,0,0
36,1,0.811378,57174.0,57199.0,176224.0,Newcastle,79.732004,medium_block,1.0,0,0
90,0,0.237960,283.0,299.0,50978.0,Newcastle,72.171697,chaotic/disruption,0.0,1,0
91,1,0.525335,1631.0,1648.0,795507.0,Newcastle,27.122273,chaotic/disruption,0.0,1,0
92,0,0.090006,1667.0,1715.0,50951.0,Auckland FC,74.534154,high_block,0.0,1,0
93,0,0.151091,4009.0,4009.0,735573.0,Newcastle,58.869028,chaotic/disruption,0.0,1,1
94,0,0.433564,4437.0,4437.0,51713.0,Auckland FC,40.190030,chaotic/disruption,0.0,1,0
95,0,0.187783,7447.0,7456.0,38673.0,Auckland FC,49.538398,chaotic/disruption,0.0,1,1
96,0,0.170461,8800.0,8808.0,795505.0,Newcastle,53.711530,chaotic/disruption,0.0,1,1
97,0,0.206808,22907.0,22917.0,795507.0,Newcastle,78.361288,chaotic/disruption,0.0,1,0
98,0,0.180064,24955.0,24955.0,795507.0,Newcastle,51.204868,chaotic/disruption,0.0,1,1
99,0,0.117465,27584.0,27598.0,38673.0,Auckland FC,69.013071,chaotic/disruption,0.0,1,1
100,0,0.189330,27601.0,27617.0,176224.0,Newcastle,48.992873,chaotic/disruption,0.0,1,1
101,0,0.466480,41626.0,41626.0,50951.0,Auckland FC,35.128081,chaotic/disruption,0.0,1,0
102,0,0.150353,48523.0,48531.0,163972.0,Auckland FC,58.670176,chaotic/disruption,0.0,1,1

In [31]:
def time_to_seconds(time_str):
    if time_str is None:
        return 90 * 60  # 120 minutes = 7200 seconds
    h, m, s = map(int, time_str.split(':'))
    return h * 3600 + m * 60 + s

file_path = f"../../data/matches/{match_id}/{match_id}_match.json"

with open(file_path, "r") as f:
    raw_match_data = json.load(f)

# The output has nested json elements. We process them
raw_match_df = pd.json_normalize(raw_match_data, max_level=2)
raw_match_df["home_team_side"] = raw_match_df["home_team_side"].astype(str)

players_df = pd.json_normalize(
    raw_match_df.to_dict("records"),
    record_path="players",
    meta=[
        "home_team_score",
        "away_team_score",
        "date_time",
        "home_team_side",
        "home_team.name",
        "home_team.id",
        "away_team.name",
        "away_team.id",
    ],  # data we keep
)


# Take only players who played and create their total time
players_df = players_df[
    ~((players_df.start_time.isna()) & (players_df.end_time.isna()))
]

# Create a flag for GK
players_df["is_gk"] = players_df["player_role.acronym"] == "GK"

# Add a flag if the given player is home or away
players_df["match_name"] = (
    players_df["home_team.name"] + " vs " + players_df["away_team.name"]
)


# Add a flag if the given player is home or away
players_df["home_away_player"] = np.where(
    players_df.team_id == players_df["home_team.id"], "Home", "Away"
)

# Create flag from player
players_df["team_name"] = np.where(
    players_df.team_id == players_df["home_team.id"],
    players_df["home_team.name"],
    players_df["away_team.name"],
)

# Figure out sides
players_df[["home_team_side_1st_half", "home_team_side_2nd_half"]] = (
    players_df["home_team_side"]
    .astype(str)
    .str.strip("[]")
    .str.replace("'", "")
    .str.split(", ", expand=True)
)
# Clean up sides
players_df["direction_player_1st_half"] = np.where(
    players_df.home_away_player == "Home",
    players_df.home_team_side_1st_half,
    players_df.home_team_side_2nd_half,
)
players_df["direction_player_2nd_half"] = np.where(
    players_df.home_away_player == "Home",
    players_df.home_team_side_2nd_half,
    players_df.home_team_side_1st_half,
)


# Clean up and keep the columns that we want to keep about

columns_to_keep = [
    "id",
    "short_name",
    "team_name",
    "player_role.name",
]
players_df = players_df[columns_to_keep]

players_df

        id     short_name                 team_name          player_role.name
0    38673         G. May               Auckland FC            Center Forward
1    51713     C. Elliott               Auckland FC                Right Back
2    50951     J. Brimmer               Auckland FC            Center Forward
3    50978     C. Timmins  Newcastle United Jets FC   Left Defensive Midfield
4   133498    F. De Vries               Auckland FC                 Left Back
5    33697    N. Pijnaker               Auckland FC          Left Center Back
6    51667        D. Hall               Auckland FC         Right Center Back
7    14736  L. Verstraete               Auckland FC        Defensive Midfield
11  735573    T. Aquilina  Newcastle United Jets FC               Left Winger
12   51009       R. Scott  Newcastle United Jets FC                Goalkeeper
13  176224      P. Cancar  Newcastle United Jets FC         Right Center Back
14  735578       M. Natta  Newcastle United Jets FC                 Left Back
15  735574      K. Grozos  Newcastle United Jets FC  Right Defensive Midfield
16   50983      D. Ingham  Newcastle United Jets FC                Right Back
17   51649   A. Å uÅ¡njar  Newcastle United Jets FC          Left Center Back
18  965685     L. Gillion               Auckland FC               Left Winger
19  795506      C. Taylor  Newcastle United Jets FC            Center Forward
20  797297   M. Scarcella  Newcastle United Jets FC        Attacking Midfield
21  560992   D. Wilmering  Newcastle United Jets FC        Attacking Midfield
22  800320       J. Vidic  Newcastle United Jets FC   Left Defensive Midfield
23   43829      N. Moreno               Auckland FC              Right Winger
24   31147       T. Smith               Auckland FC               Center Back
25  163972        M. Mata               Auckland FC            Center Forward
26  133501    L. Rogerson               Auckland FC              Right Winger
27   23418    F. Gallegos               Auckland FC        Attacking Midfield
28  795507     L. Bayliss  Newcastle United Jets FC        Attacking Midfield
29  795505       E. Adams  Newcastle United Jets FC              Right Winger
30  966120      B. Gibson  Newcastle United Jets FC            Center Forward
35  285188     A. Paulsen               Auckland FC                Goalkeeper

In [32]:
summary_df = pd.merge(results_df, players_df, left_on='rec_player_id', right_on='id', how='right')

summary_df

,predicted_class,predicted_probability,frame_start,frame_end,rec_player_id,rec_team_short,dist_to_attacking_goal,team_out_of_possession_phase_type,player_targeted_dangerous,is_drawing,is_middle_third,id,short_name,team_name,player_role.name
0,1.0,0.553058,3854.0,3866.0,38673.0,Auckland FC,47.054798,chaotic/disruption,1.0,1.0,1.0,38673,G. May,Auckland FC,Center Forward
1,1.0,0.723137,19986.0,19986.0,38673.0,Auckland FC,45.116494,medium_block,1.0,1.0,1.0,38673,G. May,Auckland FC,Center Forward
2,1.0,0.964283,47322.0,47322.0,38673.0,Auckland FC,39.455101,transition/quick_break,1.0,1.0,0.0,38673,G. May,Auckland FC,Center Forward
3,0.0,0.187783,7447.0,7456.0,38673.0,Auckland FC,49.538398,chaotic/disruption,0.0,1.0,1.0,38673,G. May,Auckland FC,Center Forward
4,0.0,0.117465,27584.0,27598.0,38673.0,Auckland FC,69.013071,chaotic/disruption,0.0,1.0,1.0,38673,G. May,Auckland FC,Center Forward
5,0.0,0.433564,4437.0,4437.0,51713.0,Auckland FC,40.190030,chaotic/disruption,0.0,1.0,0.0,51713,C. Elliott,Auckland FC,Right Back
6,0.0,0.090006,1667.0,1715.0,50951.0,Auckland FC,74.534154,high_block,0.0,1.0,0.0,50951,J. Brimmer,Auckland FC,Center Forward
7,0.0,0.466480,41626.0,41626.0,50951.0,Auckland FC,35.128081,chaotic/disruption,0.0,1.0,0.0,50951,J. Brimmer,Auckland FC,Center Forward
8,1.0,0.524581,3799.0,3799.0,50978.0,Newcastle,51.188596,chaotic/disruption,1.0,1.0,1.0,50978,C. Timmins,Newcastle United Jets FC,Left Defensive Midfield
9,0.0,0.323647,9686.0,9696.0,50978.0,Newcastle,75.306988,high_block,0.0,1.0,0.0,50978,C. Timmins,Newcastle United Jets FC,Left Defensive Midfield
10,0.0,0.237960,283.0,299.0,50978.0,Newcastle,72.171697,chaotic/disruption,0.0,1.0,0.0,50978,C. Timmins,Newcastle United Jets FC,Left Defensive Midfield
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133498,F. De Vries,Auckland FC,Left Back
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33697,N. Pijnaker,Auckland FC,Left Center Back
13,1.0,0.653909,11857.0,11887.0,51667.0,Auckland FC,56.956145,medium_block,0.0,1.0,1.0,51667,D. Hall,Auckland FC,Right Center Back
14,0.0,0.225507,10754.0,10754.0,14736.0,Auckland FC,92.865712,high_block,0.0,1.0,0.0,14736,L. Verstraete,Auckland FC,Defensive Midfield
15,1.0,0.928028,29048.0,29094.0,14736.0,Auckland FC,20.097771,medium_block,1.0,1.0,0.0,14736,L. Verstraete,Auckland FC,Defensive Midfield
16,1.0,0.893317,56777.0,56825.0,14736.0,Auckland FC,70.220155,transition/quick_break,1.0,0.0,1.0,14736,L. Verstraete,Auckland FC,Defensive Midfield
17,1.0,0.504472,7480.0,7480.0,735573.0,Newcastle,53.900933,chaotic/disruption,0.0,1.0,1.0,735573,T. Aquilina,Newcastle United Jets FC,Left Winger
18,1.0,0.618211,29047.0,29047.0,735573.0,Newcastle,94.150176,medium_block,1.0,1.0,0.0,735573,T. Aquilina,Newcastle United Jets FC,Left Winger
19,0.0,0.277043,47726.0,47726.0,735573.0,Newcastle,78.931202,high_block,1.0,1.0,0.0,735573,T. Aquilina,Newcastle United Jets FC,Left Winger
20,0.0,0.151091,4009.0,4009.0,735573.0,Newcastle,58.869028,chaotic/disruption,0.0,1.0,1.0,735573,T. Aquilina,Newcastle United Jets FC,Left Winger
21,0.0,0.393576,20549.0,20556.0,51009.0,Newcastle,101.930031,chaotic/disruption,0.0,1.0,0.0,51009,R. Scott,Newcastle United Jets FC,Goalkeeper
22,0.0,0.425580,16811.0,16823.0,176224.0,Newcastle,97.786385,chaotic/disruption,1.0,1.0,0.0,176224,P. Cancar,Newcastle United Jets FC,Right Center Back
23,1.0,0.811378,57174.0,57199.0,176224.0,Newcastle,79.732004,medium_block,1.0,0.0,0.0,176224,P. Cancar,Newcastle United Jets FC,Right Center Back
24,0.0,0.189330,27601.0,27617.0,176224.0,Newcastle,48.992873,chaotic/disruption,0.0,1.0,1.0,176224,P. Cancar,Newcastle United Jets FC,Right Center Back
25,0.0,0.196989,387.0,430.0,735578.0,Newcastle,99.575170,high_block,0.0,1.0,0.0,735578,M. Natta,Newcastle United Jets FC,Left Back
26,1.0,0.818607,1492.0,1492.0,735574.0,Newcastle,34.427403,chaotic/disruption,0.0,1.0,0.0,735574,K. Grozos,Newcastle United Jets FC,Right Defensive Midfield
27,1.0,0.737117,12012.0,12012.0,735574.0,Newcastle,76.095721,medium_block,0.0,1.0,0.0,735574,K. Grozos,Newcastle United Jets FC,Right Defensive Midfield
28,1.0,0.667639,32947.0,32953.0,50983.0,Newcastle,52.057554,medium_block,1.0,1.0,1.0,50983,D. Ingham,Newcastle United Jets FC,Right Back
29,1.0,0.874515,8011.0,8011.0,51649.0,Newcastle,18.581808,chaotic/disruption,0.0,1.0,0.0,51649,A. Å uÅ¡njar,Newcastle United Jets FC,Left Center Back
30,0.0,0.177878,23185.0,23280.0,51649.0,Newcastle,102.307695,high_block,1.0,1.0,0.0,51649,A. Å uÅ¡njar,Newcastle United Jets FC,Left Center Back
31,0.0,0.281030,29473.0,29477.0,965685.0,Auckland FC,46.435548,high_block,0.0,1.0,1.0,965685,L. Gillion,Auckland FC,Left Winger
32,1.0,0.711460,30012.0,30012.0,965685.0,Auckland FC,44.894869,medium_block,0.0,1.0,1.0,965685,L. Gillion,Auckland FC,Left Winger
33,1.0,0.891653,47570.0,47570.0,795506.0,Newcastle,81.294803,transition/quick_break,1.0,1.0,0.0,795506,C. Taylor,Newcastle United Jets FC,Center Forward
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,797297,M. Scarcella,Newcastle United Jets FC,Attacking Midfield
35,0.0,0.269521,49312.0,49312.0,560992.0,Newcastle,80.038756,high_block,0.0,1.0,0.0,560992,D. Wilmering,Newcastle United Jets FC,Attacking Midfield
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800320,J. Vidic,Newcastle United Jets FC,Left Defensive Midfield
37,1.0,0.869471,57138.0,57138.0,43829.0,Auckland FC,38.683967,chaotic/disruption,0.0,0.0,0.0,43829,N. Moreno,Auckland FC,Right Winger
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31147,T. Smith,Auckland FC,Center Back
39,0.0,0.150353,48523.0,48531.0,163972.0,Auckland FC,58.670176,chaotic/disruption,0.0,1.0,1.0,163972,M. Mata,Auckland FC,Center Forward
40,1.0,0.820613,36644.0,36644.0,133501.0,Auckland FC,30.210637,chaotic/disruption,1.0,1.0,0.0,133501,L. Rogerson,Auckland FC,Right Winger
41,1.0,0.866691,9289.0,9301.0,23418.0,Auckland FC,30.829612,low_block,0.0,1.0,0.0,23418,F. Gallegos,Auckland FC,Attacking Midfield
42,1.0,0.555331,4452.0,4452.0,795507.0,Newcastle,72.213891,medium_block,1.0,1.0,1.0,795507,L. Bayliss,Newcastle United Jets FC,Attacking Midfield
43,0.0,0.338456,10163.0,10170.0,795507.0,Newcastle,72.861567,high_block,0.0,1.0,0.0,795507,L. Bayliss,Newcastle United Jets FC,Attacking Midfield
44,1.0,0.525335,1631.0,1648.0,795507.0,Newcastle,27.122273,chaotic/disruption,0.0,1.0,0.0,795507,L. Bayliss,Newcastle United Jets FC,Attacking Midfield
45,0.0,0.206808,22907.0,22917.0,795507.0,Newcastle,78.361288,chaotic/disruption,0.0,1.0,0.0,795507,L. Bayliss,Newcastle United Jets FC,Attacking Midfield
46,0.0,0.180064,24955.0,24955.0,795507.0,Newcastle,51.204868,chaotic/disruption,0.0,1.0,1.0,795507,L. Bayliss,Newcastle United Jets FC,Attacking Midfield
47,1.0,0.574078,29369.0,29369.0,795505.0,Newcastle,84.148935,low_block,1.0,1.0,0.0,795505,E. Adams,Newcastle United Jets FC,Right Winger
48,0.0,0.178208,50131.0,50163.0,795505.0,Newcastle,65.567423,high_block,0.0,1.0,1.0,795505,E. Adams,Newcastle United Jets FC,Right Winger
49,0.0,0.170461,8800.0,8808.0,795505.0,Newcastle,53.711530,chaotic/disruption,0.0,1.0,1.0,795505,E. Adams,Newcastle United Jets FC,Right Winger
50,0.0,0.417301,17743.0,17743.0,966120.0,Newcastle,65.697584,chaotic/disruption,0.0,1.0,1.0,966120,B. Gibson,Newcastle United Jets FC,Center Forward
51,1.0,0.523097,20199.0,20199.0,966120.0,Newcastle,83.660194,chaotic/disruption,1.0,1.0,0.0,966120,B. Gibson,Newcastle United Jets FC,Center Forward
52,1.0,0.724282,28619.0,28647.0,285188.0,Auckland FC,77.325422,medium_block,1.0,1.0,0.0,285188,A. Paulsen,Auckland FC,Goalkeeper
53,0.0,0.377132,35339.0,35339.0,285188.0,Auckland FC,102.293708,chaotic/disruption,0.0,1.0,0.0,285188,A. Paulsen,Auckland FC,Goalkeeper
54,0.0,0.172894,47920.0,47920.0,285188.0,Auckland FC,100.411562,high_block,0.0,1.0,0.0,285188,A. Paulsen,Auckland FC,Goalkeeper

In [38]:
player_df_recoveries = (
    summary_df
    .groupby(['short_name', 'rec_team_short'])
    .agg(
        recoveries_count = ('predicted_class', 'count'),
        predicted_class_count = ('predicted_class', 'sum'),
        avg_pred_prob = ('predicted_probability', 'mean')
    )
    .reset_index()
)

player_df_recoveries.sort_values(by='predicted_class_count', ascending=False, inplace=True)

player_df_recoveries

,short_name,rec_team_short,recoveries_count,predicted_class_count,avg_pred_prob
11,G. May,Auckland FC,5,3.0,0.509145
17,L. Verstraete,Auckland FC,3,2.0,0.682284
13,K. Grozos,Newcastle,2,2.0,0.777862
14,L. Bayliss,Newcastle,5,2.0,0.361199
23,T. Aquilina,Newcastle,4,2.0,0.387704
0,A. Paulsen,Auckland FC,3,1.0,0.424769
2,B. Gibson,Newcastle,2,1.0,0.470199
1,A. Å uÅ¡njar,Newcastle,2,1.0,0.526196
21,P. Cancar,Newcastle,3,1.0,0.475429
7,D. Ingham,Newcastle,1,1.0,0.667639
5,C. Timmins,Newcastle,3,1.0,0.362062
6,D. Hall,Auckland FC,1,1.0,0.653909
4,C. Taylor,Newcastle,1,1.0,0.891653
10,F. Gallegos,Auckland FC,1,1.0,0.866691
15,L. Gillion,Auckland FC,2,1.0,0.496245
9,E. Adams,Newcastle,3,1.0,0.307582
20,N. Moreno,Auckland FC,1,1.0,0.869471
16,L. Rogerson,Auckland FC,1,1.0,0.820613
3,C. Elliott,Auckland FC,1,0.0,0.433564
8,D. Wilmering,Newcastle,1,0.0,0.269521
12,J. Brimmer,Auckland FC,2,0.0,0.278243
18,M. Mata,Auckland FC,1,0.0,0.150353
19,M. Natta,Newcastle,1,0.0,0.196989
22,R. Scott,Newcastle,1,0.0,0.393576